services:
  db:
    image: postgres:16
    container_name: local_hobbies_db
    environment:
      POSTGRES_DB: local_hobbies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - local_hobbies_pgdata:/var/lib/postgresql/data

volumes:
  local_hobbies_pgdata:
